ELITEFRAME_NAME = "EliteFrame"

ELITEFRAME_FRAME_DROPDOWN_NAME = "Frame"
ELITEFRAME_FRAME_DROPDOWN_DESCRIPTION = "Pick one of the frames"

ELITEFRAME_ADJUST_CHECKBOX_NAME = "Adjust Portrait"
ELITEFRAME_ADJUST_CHECKBOX_DESCRIPTION = "Toggles if the frame shall be adjusted to show frame better"

ELITEFRAME_SUBTEXT = "Making your portrait l33t"

ELITEFRAME_RARE = "Rare"
ELITEFRAME_RARE_ELITE = "Rare Elite"
ELITEFRAME_ELITE = "Elite"
ELITEFRAME_NONE = "None"